/**
 * Reference image analysis from Gemini
 */
export interface ReferenceAnalysis {
  textPlacement: string;
  objectPositions: string;
  layout: string;
  toneAndManner: string;
  background: string;
  fonts: string;
  compositionRatio: string;
}

/**
 * Creative brief generated by Claude
 */
export interface Brief {
  id: string;
  serviceId: string;
  headline: string;
  subHeadline: string;
  keyMessages: string[]; // 3 key selling points
  cta: string;
  visualDirection: string;
  toneAndManner: string;
  referenceAnalysis?: ReferenceAnalysis;
  createdAt: string;
  updatedAt: string;
}
