'use client';

import { useState, useEffect } from 'react';
import { useStepFlow } from '@/hooks/useStepFlow';
import { Loader2, RefreshCw, CheckCircle2 } from 'lucide-react';

export default function Step4ImageGeneration() {
  const {
    brief,
    referenceAnalysis,
    generatedImages,
    selectedImage,
    setGeneratedImages,
    setSelectedImage,
    nextStep,
    prevStep,
  } = useStepFlow();

  const [generating, setGenerating] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Auto-generate on mount if not already generated
  useEffect(() => {
    if (!autoGenerated && generatedImages.length === 0 && brief) {
      handleGenerate();
      setAutoGenerated(true);
    }
  }, [brief, autoGenerated, generatedImages.length]);

  const handleGenerate = async () => {
    if (!brief) {
      alert('기획안을 먼저 생성해주세요.');
      return;
    }

    setGenerating(true);
    try {
      const response = await fetch('/api/image/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brief,
          referenceAnalysis,
        }),
      });

      if (!response.ok) throw new Error('Generation failed');

      const data = await response.json();
      setGeneratedImages(data.images);
    } catch (error) {
      console.error('Image generation error:', error);
      alert('이미지 생성에 실패했습니다.');
    } finally {
      setGenerating(false);
    }
  };

  const handleRegenerate = async () => {
    if (!brief) return;

    setGenerating(true);
    try {
      const response = await fetch('/api/image/regenerate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brief,
          referenceAnalysis,
        }),
      });

      if (!response.ok) throw new Error('Regeneration failed');

      const data = await response.json();
      setGeneratedImages(data.images);
      setSelectedImage(null); // Clear selection
    } catch (error) {
      console.error('Image regeneration error:', error);
      alert('이미지 재생성에 실패했습니다.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">
          이미지 생성
        </h2>
        <p className="text-gray-600 dark:text-gray-400">
          AI가 3가지 버전의 이미지를 생성합니다
        </p>
      </div>

      {generating ? (
        <div className="text-center py-20">
          <Loader2 className="w-16 h-16 text-blue-600 dark:text-blue-400 animate-spin mx-auto mb-4" />
          <p className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            이미지 생성 중...
          </p>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">
            3개의 이미지를 동시에 생성하고 있습니다
          </p>
        </div>
      ) : generatedImages.length > 0 ? (
        <>
          {/* Generated Images Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {generatedImages.map((image) => (
              <div
                key={image.id}
                className={`
                  relative rounded-xl overflow-hidden border-4 cursor-pointer transition-all
                  ${
                    selectedImage?.id === image.id
                      ? 'border-blue-600 dark:border-blue-500 shadow-xl scale-105'
                      : 'border-gray-200 dark:border-gray-600 hover:border-blue-300 dark:hover:border-blue-500 hover:shadow-lg'
                  }
                `}
                onClick={() => setSelectedImage(image)}
              >
                {/* Placeholder Image */}
                <div className="aspect-square bg-gradient-to-br from-gray-100 to-gray-200 dark:from-gray-800 dark:to-gray-700 flex items-center justify-center">
                  <div className="text-center p-6">
                    <div className="w-20 h-20 bg-gray-300 dark:bg-gray-600 rounded-full mx-auto mb-4 flex items-center justify-center">
                      <span className="text-3xl font-bold text-gray-500 dark:text-gray-300">
                        {image.variant}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-300 font-medium">
                      버전 {image.variant}
                    </p>
                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
                      이미지 생성 API 연동 필요
                    </p>
                  </div>
                </div>

                {/* Selection Indicator */}
                {selectedImage?.id === image.id && (
                  <div className="absolute top-4 right-4 bg-blue-600 dark:bg-blue-500 text-white p-2 rounded-full">
                    <CheckCircle2 className="w-6 h-6" />
                  </div>
                )}

                {/* Select Button */}
                <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 dark:from-black/80 to-transparent p-4">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setSelectedImage(image);
                    }}
                    className={`
                      w-full py-2 rounded-lg font-semibold transition-colors
                      ${
                        selectedImage?.id === image.id
                          ? 'bg-blue-600 dark:bg-blue-500 text-white'
                          : 'bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-600'
                      }
                    `}
                  >
                    {selectedImage?.id === image.id ? '선택됨' : '이 이미지 선택'}
                  </button>
                </div>
              </div>
            ))}
          </div>

          {/* Regenerate Button */}
          <div className="text-center mb-8">
            <button
              onClick={handleRegenerate}
              disabled={generating}
              className="inline-flex items-center gap-2 px-6 py-3 border-2 border-purple-600 dark:border-purple-500 text-purple-600 dark:text-purple-400 rounded-lg font-semibold hover:bg-purple-50 dark:hover:bg-purple-900/20 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw className="w-5 h-5" />
              새로운 이미지 3개 생성
            </button>
          </div>

          {/* Selected Image Info */}
          {selectedImage && (
            <div className="bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-800 rounded-xl p-6 mb-8">
              <h3 className="font-bold text-lg mb-2 text-blue-900 dark:text-blue-300">
                선택된 이미지: 버전 {selectedImage.variant}
              </h3>
              <p className="text-sm text-blue-700 dark:text-blue-400">
                이 이미지를 기반으로 채널별 광고 소재를 제작합니다
              </p>
            </div>
          )}
        </>
      ) : (
        <div className="text-center py-20">
          <p className="text-gray-500 dark:text-gray-400 mb-4">이미지를 생성하지 못했습니다</p>
          <button
            onClick={handleGenerate}
            className="px-6 py-3 bg-blue-600 dark:bg-blue-500 text-white rounded-lg font-semibold hover:bg-blue-700 dark:hover:bg-blue-600 transition-colors"
          >
            이미지 생성 시작
          </button>
        </div>
      )}

      {/* Navigation */}
      <div className="flex justify-between">
        <button
          onClick={prevStep}
          className="px-6 py-3 border-2 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg font-semibold hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          이전 단계
        </button>

        <button
          onClick={nextStep}
          disabled={!selectedImage}
          className={`
            px-8 py-3 rounded-lg font-semibold transition-all
            ${
              selectedImage
                ? 'bg-green-600 dark:bg-green-500 text-white hover:bg-green-700 dark:hover:bg-green-600 hover:shadow-lg'
                : 'bg-gray-200 dark:bg-gray-700 text-gray-400 dark:text-gray-500 cursor-not-allowed'
            }
          `}
        >
          {selectedImage ? '채널별 광고소재 제작하기' : '이미지를 선택해주세요'}
        </button>
      </div>
    </div>
  );
}
